### PR TITLE
Interchange outputs with inputs in docstring

### PR DESCRIPTION
**Pull request by namannimmo10**
`self._shape` is equal to `(self._outputs, self._inputs)`.

### CODE REVIEW

**Comment by ilayn** [comment]
Oh my. So grateful that you are plowing through that file :) I was going a bit insane, thanks.

**Comment by namannimmo10** [comment]
@ilayn, where do we typically use a transfer function matrix? Like any practical applications?

**Comment by ilayn** [comment]
@namannimmo10 It mostly comes from the filtering outputs; for example you have a MIMO system and you want to quickly implement input/output filtering. Say I want to implement a notch filter on the second input and some lowpass filter on the third output. Then you want to quickly perform this operation (take a 4x3 MIMO system)

```python
G_in = diag(1, Transfer(..some notch filter in TF form..), 1)
G_out = diag(1, 1, Transfer(...some low pass filter...), 1)
G_result = G_out @ G @ G_in
```

You can also do some triangular MIMO system which is also used a lot in H_inf control such as `G = [[G1, 0], [G2, G3]]` and forming these entries quickly makes MIMO TFM useful. So it is mostly conveninence. None of the number crunching methods are recommended over TFMs and as soon as possible we switch to State Representations.

**Comment by namannimmo10** [comment]
@ilayn, Thanks a lot for this!

**Comment by namannimmo10** [comment]
Hey, @ilayn! We have a GSoC student developer who is working on the Control module of SymPy, which I developed last summer. We will complete the MIMO TFM, State-space functionality, and some graphical analyses (root_locus, bode).
It would be nice if you could chime in when you have time! :) See https://github.com/sympy/sympy/issues/21539

**Comment by ilayn** [comment]
@namannimmo10 Thanks for the ping. Let me know if I can be of use. I guess I'll wait for the PR then

**Pull request merged**
