### PR TITLE
DOC: Update haroldpolyadd function

### PR DESCRIPTION
**Pull request by whzup**
Updated the `haroldpolyadd` function. It now trims the zeros of the output
instead the zeros of the input. Improved the docstring with a parameter
and return list.

If you like these changes I can change the `haroldpolymult` function as well.

### CODE REVIEW

**Comment by ilayn** [comment]
Just to clarify, do you want to trim the input or output or both ? I am wondering if all options should be exposed with `trim_input` and `trim_output`. 

The use cases are (as far as I can see):
 - Trim input: The inputs can be zero padded at the front but output should be whatever the trimmed sizes are Example `[0, -2, 1, 2]` and `[0, 2, -1, 1]` -> `[0, 0, 3]`
- Trim output: The inputs can be zero padded at the front but output should be trimmed Example `[0, 0, 1, 2]` and `[0, 0, -1, 1]` -> `[3]`
 - Trim input and output: The inputs can be zero padded at the front and the output should be trimmed Example `[0, -2, 1, 2]` and `[0, 0, 0, 2, -1, 1]` -> `[3]`
 - Don't touch anything (both false): Example `[0, -2, 1, 2]` and `[0, 0, 0, 2, -1, 1]` -> `[0, 0, 0, 0, 0, 3]`

**Comment by whzup** [comment]
Hmm, well the question is whether or not one or the other is necessary 🤔 Although, if you provide default `True`'s it might actually be no problem. Both would do it as well 👍

**Comment by ilayn** [comment]
I played with different versions and it has a bit of effect on the rest of the library since I do a lot of stuff regarding the MIMO transfer functions. Hence it is a bit of a bigger surgery.

 Do you mind keeping this PR to the docstrings? 

Then it is easier to chop the rest into smaller pieces later.

**Comment by ilayn** [comment]
@whzup  Sorry it took a while to spare some time for this. Now it should be a bit better to work on. I've enabled the `intersphinx` extension to link automatically to Numpy.

**Comment by ilayn** [comment]
I've closed and opened to try to trigger Travis,

**Comment by ilayn** [comment]
All green. Merging. Thanks @whzup !

**Pull request merged**
